declare module '@ashthornton/asscroll'
declare module '@loadable/component'
declare module 'gatsby-plugin-dark-mode'
declare module 'gatsby-plugin-transition-link'
declare module '*jpg'
declare module '*png'
declare module 'gatsby-plugin-mailchimp'
declare module 'lodash.map'